[features]
seeds = false
skip-lint = false
[programs.localnet]
anchor_counter = "9sMy4hnC9MML6mioESFZmzpntt3focqwUq1ymPgbMf64"

[registry]
url = "https://api.apr.dev"

[provider]
cluster = "localnet"
wallet = "/Users/quinlanalexander/.config/solana/id.json"

[scripts]
test = "yarn run ts-mocha -p ./tsconfig.json -t 1000000 tests/**/*.ts"
